### ISSUE TITLE
Randomly crashes when compiling the schema with `import_types` in tuples.

### ISSUE THREAD

**Issue by hickscorp** [absinthe-graphql/absinthe#835]
Note that this bug is showing up inconsistently and I'm unable to have a clear reproducible scenario.

Basically, when importing types, we had something working with Absinthe 1.4 that looked like this:

```
  # Absinthe custom types.
  import_types Absinthe.{Plug.Types, Type.Custom}
  # General types.
  import_types MyAppWeb.Schema.QueryFilterTypes
  # User related stuff.
  import_types MyAppWeb.Schema.User.{Types, RootQueries}
  # Session related stuff.
  import_types MyAppWeb.Schema.Session.Types
  # Keypair related stuff.
  import_types MyAppWeb.Schema.Keypair.Types
  # Document related types.
  import_types MyAppWeb.Schema.Document.{Types, RootQueries, IsDocumentable}
  # Label related types.
  import_types MyAppWeb.Schema.Label.{Types, Mutations, IsLabelable}
  ...
```
With Absinthe 1.5, this randomly crashes the schema compilation - sometimes it works - sometimes it doesn't.

When it does crash, we get this error:

```
== Compilation error in file lib/myapp_web/schema.ex ==
** (ArgumentError) module Elixir.MyAppWeb.Schema.User.Types is not available
    lib/absinthe/schema/notation.ex:1528: anonymous fn/5 in Absinthe.Schema.Notation.do_import_types/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/absinthe/schema/notation.ex:1522: Absinthe.Schema.Notation.do_import_types/3
    expanding macro: Absinthe.Schema.Notation.import_types/1
    lib/myapp_web/schema.ex:16: MyAppWeb.Schema (module)
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Once the error shows up, the only way to get it going again is to use the following notation instead:

```
  # Absinthe custom types.
  import_types Absinthe.Plug.Types
  import_types Absinthe.Type.Custom
  # General types.
  import_types MyAppWeb.Schema.QueryFilterTypes
  # User related stuff.
  import_types MyAppWeb.Schema.User.Types
  import_types MyAppWeb.Schema.User.RootQueries
  # Session related stuff.
  import_types MyAppWeb.Schema.Session.Types
  # Keypair related stuff.
  import_types MyAppWeb.Schema.Keypair.Types
  # Document related types.
  import_types MyAppWeb.Schema.Document.Types
  import_types MyAppWeb.Schema.Document.RootQueries
  import_types MyAppWeb.Schema.Document.IsDocumentable
  # Label related types.
  import_types MyAppWeb.Schema.Label.Types
  import_types MyAppWeb.Schema.Label.Mutations
  import_types MyAppWeb.Schema.Label.IsLabelable
```

Please keep this issue open and I'll try to add information as the bug comes and goes.

**Comment by binaryseed** [comment]
Would you mind trying this out again with `master` now that https://github.com/absinthe-graphql/absinthe/pull/865 has been merged?
