### ISSUE TITLE
Schema fails to compile on elixir 1.7.0-rc.0

### ISSUE THREAD

**Issue by lukaszsamson** [absinthe-graphql/absinthe#577]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.0-dev (c36b2c907) (compiled with Erlang/OTP 21)
* Absinthe version (mix deps | grep absinthe): * git 1.4 branch

### Expected behavior

Clean compilation as on elixir 1.6

### Actual behavior
```
== Compilation error in file lib/my_app_web/schema.ex ==
** (Absinthe.Schema.Error) Invalid schema:
Elixir.MyApp.Web.Schema:0: The root query type must be implemented and be a of type Object
  
  
  #Example
  defmodule MyApp.Schema do
    use Absinthe.Schema
  
    query do
      #Fields go here
    end
  end
  
  --------------------------------------
  From the graqhql schema specifiation
  
  A GraphQL schema includes types, indicating where query and mutation
  operations start. This provides the initial entry points into the type system.
  The query type must always be provided, and is an Object base type. The
  mutation type is optional; if it is null, that means the system does not
  support mutations. If it is provided, it must be an object base type.
  
  Reference: https://facebook.github.io/graphql/#sec-Initial-types


    lib/absinthe/schema.ex:271: Absinthe.Schema.__after_compile__/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
```

**Comment by benwilson512** [comment]
Well we've got an RC now and the issue persists. Investigating.

**Comment by drincruz** [comment]
@benwilson512 I've pulled down your changes locally and am testing things out and this issue does not seem to be present in what is in master.  🎊 👍  I think you can close this issue?

**Comment by phikes** [comment]
This is still happening with 1.7.1 which is the latest stable version of Elixir.

**Comment by benwilson512** [comment]
@phikes run `mix deps|grep absinthe`. If you aren't on the latest version, upgrade.

**Comment by phikes** [comment]
Of course, my bad! Thank you very much and sorry for the inconvenience!
