### ISSUE TITLE
Compilation error when importing types

### ISSUE THREAD

**Issue by devonestes** [absinthe-graphql/absinthe#684]
### Environment

* Elixir version (elixir -v): 1.8.1
* Absinthe version (mix deps | grep absinthe): 1.5.0-alpha.2
* Client Framework and version (Relay, Apollo, etc): N/A

### Expected behavior

Normal compilation like on 1.4.x

### Actual behavior
When I attempt to compile my app, I see the following error raised:

```
== Compilation error in file lib/potion_web/schema.ex ==
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2    
    
    The following arguments were given to :elixir_aliases.do_concat/2:
    
        # 1
        [{:__MODULE__, [line: 56], nil}, :Types]
    
        # 2
        "Elixir"
    
    lib/absinthe/schema/notation.ex:1454: Absinthe.Schema.Notation.do_import_types/3
    expanding macro: Absinthe.Schema.Notation.import_types/1
    lib/potion_web/schema.ex:56: PotionWeb.Schema (module)

```

### Relevant Schema/Middleware Code

This is in my schema, which works in 1.4 but not on the 1.5 alpha:

```elixir
  import_types(__MODULE__.Types.{
    Announcements,
    Authentications
  })
```

Looks like there's some AST that needs to be expanded somewhere in
that macro to resolve module aliases properly.

**Comment by rossvz** [comment]
I'm getting this exact error on `1.5.0-rc.2`: 
```
== Compilation error in file lib/instinct_api/schema/schema.ex ==
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2

    The following arguments were given to :elixir_aliases.do_concat/2:

        # 1
        [{:__MODULE__, [line: 8], nil}, :Types]

        # 2
        "Elixir"

    lib/absinthe/schema/notation.ex:1546: Absinthe.Schema.Notation.do_import_types/3
    expanding macro: Absinthe.Schema.Notation.import_types/1
    lib/instinct_api/schema/schema.ex:8: Instinct.API.Schema (module)
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Using syntax like @devonestes 
```elixir
import_types(__MODULE__.Types.{
    Atype,
    Btype,
    Ctype
})
```
