### PR TITLE
Support self contained schemas using `import_types` from `__MODULE__`

### LINKED ISSUE #684: Compilation error when importing types
### Environment

* Elixir version (elixir -v): 1.8.1
* Absinthe version (mix deps | grep absinthe): 1.5.0-alpha.2
* Client Framework and version (Relay, Apollo, etc): N/A

### Expected behavior

Normal compilation like on 1.4.x

### Actual behavior
When I attempt to compile my app, I see the following error raised:

```
== Compilation error in file lib/potion_web/schema.ex ==
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2    
    
    The following arguments were given to :elixir_aliases.do_concat/2:
    
        # 1
        [{:__MODULE__, [line: 56], nil}, :Types]
    
        # 2
        "Elixir"
    
    lib/absinthe/schema/notation.ex:1454: Absinthe.Schema.Notation.do_import_types/3
    expanding macro: Absinthe.Schema.Notation.import_types/1
    lib/potion_web/schema.ex:56: PotionWeb.Schema (module)

```

### Relevant Schema/Middleware Code

This is in my schema, which works in 1.4 but not on the 1.5 alpha:

```elixir
  import_types(__MODULE__.Types.{
    Announcements,
    Authentications
  })
```

Looks like there's some AST that needs to be expanded somewhere in
that macro to resolve module aliases properly.

### PR DESCRIPTION
**Pull request by dkarter**
[Closes #684]

Support using `import_types` using the `__MODULE__` special form.
According to #684, This was supported previously in 1.4, but since 1.5
it has been erroring out in compile time with the following:

```
== Compilation error in file lib/potion_web/schema.ex ==
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2

    The following arguments were given to :elixir_aliases.do_concat/2:

        # 1
        [{:__MODULE__, [line: 56], nil}, :Types]

        # 2
        "Elixir"

    lib/absinthe/schema/notation.ex:1454: Absinthe.Schema.Notation.do_import_types/3
    expanding macro: Absinthe.Schema.Notation.import_types/1
    lib/potion_web/schema.ex:56: PotionWeb.Schema (module)
```

### CODE REVIEW

**Comment by benwilson512** [comment]
Thanks!
